services:
  proximamente:
    image: proximamente:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proximamente
    hostname: proximamente
    environment:
      API_URL: ${API_URL}
    restart: unless-stopped
    networks:
      - proxy
      - fullstack

networks:
  proxy:
    external: true
  fullstack:
    external: true
